const { chromium } = require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES ? process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES + '/playwright' : 'playwright');
const path = require('node:path');
const fs = require('node:fs');
(async () => {
 const browser = await chromium.launch({executablePath:process.env.TEMPO_VIVO_CHROME || undefined,headless:true,args:['--no-sandbox','--disable-dev-shm-usage']});
 const page = await browser.newPage({viewport:{width:1080,height:1100},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(String(e)));
 await page.goto('file://'+path.resolve(__dirname,'../demo.html'));
 await page.getByText('Verificações do card',{exact:true}).click();
 await page.getByRole('button',{name:'Executar verificações'}).click();
 await page.waitForFunction(()=>window.tvTestResult!==null);
 const result=await page.evaluate(()=>window.tvTestResult);
 console.log(JSON.stringify({result,errors},null,2));
 await page.getByText('Verificações do card',{exact:true}).click();
 await page.locator('.card-wrap').screenshot({path:path.resolve(__dirname,'../docs/card-sol.png')});
 await page.getByRole('button',{name:'Chuva',exact:true}).click();
 await page.waitForTimeout(3400);
 await page.locator('.card-wrap').screenshot({path:path.resolve(__dirname,'../docs/card-chuva.png')});
 await page.getByRole('button',{name:'Mostrar cômodos'}).click();
 await page.locator('#width').selectOption('320');
 await page.waitForTimeout(400);
 await page.locator('.card-wrap').screenshot({path:path.resolve(__dirname,'../docs/card-celular.png')});
 const overflow=await page.locator('#card').evaluate(e=>({width:e.clientWidth,scroll:e.shadowRoot.querySelector('ha-card').scrollWidth}));
 console.log(JSON.stringify({mobileOverflow:overflow}));
 await page.getByRole('button',{name:'Editar sensores'}).click();
 await page.locator('#editor').screenshot({path:path.resolve(__dirname,'../docs/editor.png')});
 await browser.close();
 fs.writeFileSync(path.resolve(__dirname,'../docs/test-results.json'),JSON.stringify({result,errors,mobileOverflow:overflow},null,2));
 if(!result.passed||errors.length||overflow.scroll>overflow.width+1)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
